INSERT INTO Building (id, fmxBuildingName, name) VALUES (209874, 'Pasco High School', 'Pasco High School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210019, 'Chiawana High School', 'Chiawana High School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210020, 'Columbia River Elementary', 'Columbia River Elementary');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210021, 'Marie Curie Elementary', 'Curie STEM Elementary School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210181, 'Rosalind Franklin Elementary', 'Franklin STEM Elementary School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210014, 'Angelou Elementary', 'Maya Angelou Elementary School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210187, 'McClintock Elementary', 'McClintock STEM Elementary School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210190, 'McLoughlin Middle School', 'McLoughlin Middle School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210192, 'Ellen Ochoa Middle School', 'Ochoa Middle School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210194, 'Ray Reynolds Middle School', 'Reynolds Middle School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210195, 'Virgie Robinson Elementary', 'Robinson Elementary School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210197, 'Isaac Stevens Middle School', 'Stevens Middle School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210199, 'Three Rivers Elementary', 'Three Rivers Elementary School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210198, 'Mark Twain Elementary', 'Twain Elementary School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210015, 'Booth Building', 'Booth Admin - Pasco');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210178, 'Delta High School', 'Delta High School');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210200, 'Whittier Elementary', 'Whittier Elementary');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210180, 'Emerson Elementary School', 'Emerson Elementary');
INSERT INTO Building (id, fmxBuildingName, name) VALUES (210182, 'Robert Frost Elementary', 'Frost Elementary');